### ISSUE TITLE
5-15 Reports Week 1

### ISSUE THREAD

**Issue by JarrettAzar** [RickyNM/TableTopRPGToolbox#15]
Comment your 5-15 report here

**Comment by JarrettAzar** [comment]
11/8/2017
For the week of 11/5
For Jarrett

	This week was mainly a planning week. Our main goal was to get roles figured out, do some framework research and finish the code of conduct. I was able to define my role (UI Manager), and find out how to get code from other repositories on GitHub since none of us knew how to do that. I also accomplished figured out the project tab on GitHub and how to organize files into folders. So far, the team is working, in that we are all meshing well and following our responsibilities. Any improvements that could be made have yet to surface so far. I am feeling great and I think the team is working well together and I think we have the ability to really finish this project. A good idea would be to start coding, which the group has already started working on, because our planning phase is almost over and we should start to code as soon as possible. My concrete step is having a working UI landing page by our Sunday meeting. For next week we want to have some code, even if it is empty shells, and to finalize our open source projects from which we will be pulling some code.

**Comment by Halfcreative** [comment]
My 5-15 report is also on our google drive in a folder entitled 5-15 reports

The TableTopRPGToolbox team, (Referred to as TTRPGTT from beyond this point) was formed. Before our first congregation, meetings were scheduled for Sundays from 1pm to 2:30pm, Wednesdays from 9:30am to 10:30am, and Fridays from 9:30am to 11 am. Friday meetings were decided to be an extra half an hour longer, in order to meet with Dr.Kussmaul and review progress. During the first meeting on Sunday November 5th,  I (Alan Sato) was assigned to be the secretary for the team, and GitHub was chosen as our project management suite. The remainder of the meeting was spent familiarizing ourselves with the GitHub environment. In between the group’s first two meetings, each member was assigned a minor task to complete for the next meeting on Wednesday November 8th. In that meeting, each member brought their completed assignments, and insights regarding the project were shared. The Code of Conduct was then developed,finalized and signed by each group member. To conclude the meeting tasks were assigned to each member for completion by Friday November 10th.
Discussion within the group is slow to start, but as members become more vocal and explicit, the discussion moves forward effectively. The team has been easy to contact, and delightful to correspond with. The group finds an effective balance of productive discussion as well as fun banter that keeps spirits high. I am hopeful that as the workload increases the balance is effectively maintained.

**Comment by RickyNM** [comment]
11/8/17 
For the week of 11/5/17
For Ricky Morash
For this week I intended to get sample versions of each of the class types. In place of this I spent a lot of time figuring out how the files should be organised and which files we will need, which is now stored in FileOrganization.txt. I also drew up potential plans for each of the classes which is in ClassHierarchy.txt. After talking with the group I made a few changes to the ClassHierarchy.txt to demonstrate a change that we all thought would be best. I think that Github will be a good place for us to work on this because it allows us to manage the code from different people well.
I think that we could improve by all being ready to start at the beginning of each of our meetings, we did not really start today's meeting until about 10 when it was supposed to start at 9:30. Overall I feel a bit anxious but happy. I am more then a little worried that my idea and way of thinking about the project is unreasonable and will prevent it from happening. 
At the moment I cannot think of anything that fits what I am interpreting the good idea section as. My task for the coming week is to make shells for each of the classes and to implement the more important classes.

**Comment by StriderJonak** [comment]
Week #1 5:15 Report
Strider Jonak (11/08/2017)

As the first round of meetings progressed, the TTRPGTT team focused largely on the required documentation that will aid the project in the coming weeks. Among them, the Code of Conduct, individual objective statements, and README documents were uploaded to the designated file manager, GitHub.  We had also designated Alan Sato as our meeting-progress recorder and recognized Ricky Morash as the lead vision in the project.
I expressed interest in handling the character creation assets and will be referencing my objective statement as well as speaking with Ricky about integrating as many database properties as possible into a working example of the character object. I will be using Java to create superclasses for all animate objects and subclasses for monsters and characters. It is my goal to have a framework that can pass and set properties from the command line - and hopefully read/write to a JSON file in the near future. Randomization of these properties is also being considered, which may utilize open-source code.
Finally, we decided upon a reviewer rotation in which any merges to the master branch I wish to push will need to be reviewed by Ricky Morash and I will fulfill the same role for Alan Sato.
I am excited to see the preliminary steps to getting this project off the ground and will be very relieved when we have several pieces of the project working independently before coming together for the larger vision. I can certainly stand to become more familiar with GitHub and JSON files in general.
I think that splitting the work in such a way was a good idea as we are all personally responsible for a critical role in the TTRPGTT experience. I would like to see our synergy increase as the project proceeds in communication, documentation, and programming - I do like the energy of this team.

**Comment by RickyNM** [comment]
Week 1 5-15
for Team Dungeons and Dragons Toolbox (now Table Top RPG Toolbox)
11/9/17
In the past week the group has settled on Github as our code repository and task managing system. In addition to this we made our code of conduct and found some opensource code that we think will be helpful. We also made some progress on documenting what we think we will need in terms of files and classes. Lastly we have settled on a peer review of code process and which sections of the project each of us will be working on.
Our goals for the coming week are to select which of the open source code we will be using and get it into our repository, have at least shells for all of our classes, and to have a start to a user interface.
The team is excited to work together with only a few worries expressed by one member relating to being able to finishing the project.
As for things to improve that centered mostly on starting on time, having a proper discussion from the beginning rather than drag out the opening, and increasing the synergy of the group.
Overall we have made some decent progress for only a week and it seems like the group will be able to work well together.
