### ISSUE TITLE
5-15 Reports Week 2

### ISSUE THREAD

**Issue by StriderJonak** [RickyNM/TableTopRPGToolbox#28]
Comment your reports below

**Comment by StriderJonak** [comment]
Week #2 5:15 Report
Strider Jonak (11/16/2017)

Round two of meeting with the TTRPGTT team revolved around keeping up to date with the progress of our members and coordinating concepts to orient each component to fit as a part of the project together. My primary progress has been in writing the Alive superclass that will extend the Character and Monster classes. I have taken our supervisor's advice and began separating the code that handles the information from the code that stores the information in a separate file. The logic for this is to prepare for an alternative data storage format such that it can more easily be changed as the project evolves. I have been speaking most with Ricky about the nature and organization of the properties of the Alive and Character classes - the most significant idea is to have 'base' properties and 'effective' properties that will more easily allow a dynamically changing character to iterate or regress with levels and external bonuses.
This week we will be doing revisions by Friday and we changed our Wednesday meetings to 3:30pm to increase productivity. I was beginning to create a createCharacter class but was told that this could be achieved with open source code later in the project, so instead I will focus on a high-level approach and changes to the Alive and Character classes.
We certainly felt that this week had diminishing returns in progress but that may be attributed to the logarithmic curve of the project. I have certainly had my nose in trying to simplify and reduce duplicate code in my java files and could improve on communication with my team on that front. I am of the mentality that although the progress has slowed somewhat, the most important thing is to keep steady progress. I will keep the articles on peer code review in mind this round of the project. I hope we can start to piece the code together come mid-next week!

**Comment by RickyNM** [comment]
11/16/2017
For the week of 11/12/2017
For Ricky Morash

In the past week I have worked on making all of the classes that we need for the project. I feel like I didn't accomplish as much as I could have in the past week but that I am not to far behind that we won't be able to get the project done. 

I think that it would be helpful for all of us to keep our changes to the code on the github repository rather than only put the changes on the repository once we finish that portion. I will put my code up more frequently and ask the others to do so.

I feel pretty good about the project. I worry a little whenever I think about how much time we have left but I think that we will have something that we can present on at the end of the semester. I think that the group works well together but the have been a handful of issues with people missing or showing up late to meetings. We are thinking about moving the meeting times to try and encourage everyone to show up.

For the next week I am going to try to make sure that all of the classes have everything that they need and have good restrictions on what can be inputted into the set methods.

**Comment by RickyNM** [comment]
11/16/17
For the Week of 11/12/2017

For Jarrett

This week everyone has been hard at work, and progress has understandably felt very slowed. The groups main goal for this week was to continue working on our current tasks, which may need to be rethought as they may be too large and vague to get done in a weeks time. My role as the UI Manager has been going somewhat smoothly, and I am progressing towards a working prototype of the UI systems. As of right now the team dynamic is going well, although recently some members have been late or missed meetings. After week 2 I still believe that we will be able to get the project Version 1.0 done. Hopefully we dont run into major speed bumps any time soon.

**Comment by RickyNM** [comment]
11/17/2017
Week of 11/12/2017
for D&D Toolbox Team

We have all noticed a slowdown in our productivity and have had some issues with a member missing some meetings and not responding to any communications. The slow down we are not to worried about because all of us still think that we will be able to get our project done to a reasonable extent. We will be issuing a first warning to the one member who has had trouble making it to the meetings. We are also going to try to change our meeting times so as to make it easier for everyone to attend.

We have managed to get a fair amount done but each of us have a lot more that we can work on. For the next week we will try to make it so that all of the classes are fully finished and have appropriate restrictions on what can be inputted for any of the instance variables, that we have a GUI that has multiple pages, and that we will have everything we need for the character creation.
