### ISSUE TITLE
5-15 Reports Week 3

### ISSUE THREAD

**Issue by RickyNM** [RickyNM/TableTopRPGToolbox#41]
Put your 5-15s here

**Comment by RickyNM** [comment]
11/29/17
for the week of 11/26/17
For Ricky Morash of Team D&DToolbox
My plan for this week was to finalize the classes that I am working on and get started on reading from and writing to files so that the data is saved between runs of the program. I have a final version for all but two of the classes because I was struggling with how to handle the hash tables. I have concluded that I will just have pared lists instead because I already know how to handle them. I should be able to use that to finish the last two classes tomorrow and I will see if I cannot start work on reading and writing the files then. Once I have reading and writing done I will work on a main file that will control starting the program. Overall I feel pretty good about the project because we have all put in a good amount of work and I think that we will have something working to be presented by the time we present. I am sure that we will not get to some of the items that I thought would be feasible at the beginning but I realize now just how large a project this is and how getting any of it to work properly is an accomplishment in and of itself.

**Comment by JarrettAzar** [comment]
11/29/17
For the week of 11/26/17 and Thanksgiving Break
For Jarrett Azar

My plan for this week is and was to continue using the NetBeans IDE to complete our UI needs. It has been working well as it has a drag and drop system and writes back end, easily editable code for us in Java. Once other files are completed for the character class, I will begin implementing set methods to the buttons and information from character creation. I feel pretty good about completing that portion of the project and having something to present for the final. Our Wednesday meeting time worked much better for the group and it seems like we were all more awake and active. I think we as a team are working fairly smoothly and getting far in the project. I am excited to continue work on the project and work with the team.

**Comment by StriderJonak** [comment]
11/30/17
For the week of 11/26/17
For Strider Jonak

My priorities for this week rest with completing the Alive, Character, and Monster classes.  I have acquired a Player's Handbook to cross-reference the properties of each class and compile each without issue. Due to the fact that the databases are not yet compatible with these three classes, I will be constructing a mockup character to illustrate the functionality of the programming through the terminal. In terms of the finale of the class, I can promise a functioning standalone character but when it comes to integrating into the game engine, I still have some doubts. My primary concern is to have one project that ties these classes together, even if they are not perfectly representative of the vision of the project at this point in time. I am confident in the progress my teammates have made and my target is to complete the classes I am responsible for as 1:1 as I can.

**Comment by RickyNM** [comment]
11/30/17
For the week of 11/26/17
For Team D&DToolbox
In the past week there has been steady progress towards our goals and realizations about what is and is not feasible to finish in the time that we have. Our initial goals for the project were far more ambitious then any of us realized but we should have a working version of our product, tho it will be missing many of the elements that we originally hoped to have. This has decreased the overall moral a bit but that is only because all of us want to see the product in all of its glory not the simplest version that will likely be presented. Following our last meeting we have shifted priorities slightly to make the most of the time that we still have. It also seems like the change of our Wednesday meeting time was beneficial to our productivity during the meeting.
