### ISSUE TITLE
5-15 Reports Week 4

### ISSUE THREAD

**Issue by JarrettAzar** [RickyNM/TableTopRPGToolbox#49]
12/7/17
For the Week of 12/3
For Jarrett

	This week the group mainly focused on finalizing what we needed done for the presentation, and the venture proposal. I have gotten our UI to a very solid point this past week as it is now able to create a character and store that information. Our group has been obviously stressed but working diligently to make sure we meet our deadlines for the project. We had an extra meeting today, on Thursday, to allow more team time to work on the project. I feel very confident that we will complete the last few pieces before the presentation, and that at least I am on my way to having 20 complete pages of material to hand in. I feel great about the group and where we are at and the project is shaping up wonderfully.

**Comment by RickyNM** [comment]
12/7/17
For the Week of 12/3/17
For Ricky

For the past week I have been working on my sections of the Venture Proposal and Presentation and being able to read a character from a file. I have my slides for the Presentation done and have most of my work for the Proposal done, I am just not really sure what is needed for the estimates and schedules section so I am hesitant to put my work on redmine. As for the reading a character from a file, I have some work done on it but I have realized that there are a few structural things that should be changed before it is completed so I am going to work on it after the presentation so that it is done right. Overall I feel pretty good about the project because we have gotten a lot of work done and I am excited to keep working on it after the semester ends.

**Comment by StriderJonak** [comment]
12/07/17
For the Week of 12/07/17
Strider Jonak

The outline that the group delegated for the week included a integration of the JPanel and Character files. Specifically, being able to display the Character properties within the JPanel frame. Jarrett and I worked in prioritizing the instance variables that most significantly impacted character creation. It was my personal responsibility to update the example character in AliveTest.java from a Alive object (superclass) into the Character object - one that relies on the integration of CharacterClass (Roles), Race, and Background objects in order to present a convincing character. So far, the example characater models Gandalf the Gray after modifying his key properties becomes Gandalf the White (our early demonstration of a dynamic character object.)
As it stands, making Gandalf in the JPanel window is a huge relief for the team, it really feels like the first big link in the project. However, I am very aware of how unfinished our database for Items, SpellAbilities, Races, Backgrounds, and CharacterClasses are. To fully flesh out these databases we would need and sacrifice time we just don't have for a polish that might not be fully seen in the final presentation of the RPGToolbox. Therefore, my efforts have shifted to the Needs & Competitive Analysis portions of our venture proposal as well as addressing Risk. The biggest step forward would be to have a convincing presentation so as to build support in the project's future growth.
I've learned that Software Engineering has a very steep learning curve, but with practice, trivial things like programming-styles and variable naming conventions will become more uniform and reduce the confusion between negotiating the relationship between two previously adjoined files. Finally, as the project nears it's first major milestone I can say with confidence that the documentation of a project can really make or break the team's confidence in the project. Luckily, RPGToolbox has been meeting satisfactory documentation and I can sense it's beneficial effect on our team collective mind to have it nearly out of the way. I look forward to our first venture proposal and expect to learn much from the experience.

**Comment by RickyNM** [comment]
12/7/17
For the Week of 12/3/17
For D&DToolbox

In the past week we have managed to integrate the user interface with the character class and create a character object from the user interface where we can see the results of a toString call. This should be ready to write to a file but that has not been explicitly tested as of yet. The ability to read back what was written to the file looks like it will not happen in time for the presentation because there are some structural differences between some of the files because no style sheet was used and there was insufficient communication between those involved to indicate how they were working differently. While this would not have been an issue if it was realized a week or two ago there is now not enough time before the presentation to ensure that all of the required changes would be made properly. As such we have instead focused on making sure that we have a good presentation and Venture Proposal. We are now only a few sections short of having our Venture Proposal done and just need to practice running through our presentation a few times. The moral of the group is quite high as we are all proud of what we have accomplished even if it might not be as much as we thought we would at the beginning of the project. For the next week we will polish our presentation, finish the Venture Proposal, and return to the read from file as time permits.
